export const NIPResponses: { [key: string]: string } = {
  '00': 'Approved or completed successfully',
  '01': 'Status unknown, please wait for settlement report',
  '03': 'Invalid Sender',
  '05': 'Do not honor',
  '06': 'Dormant Account',
  '07': 'Invalid Account',
  '08': 'Account Name Mismatch',
  '09': 'Request processing in progress',
  '12': 'Invalid transaction',
  '13': 'Invalid Amount',
  '14': 'Invalid Batch Number',
  '15': 'Invalid Session or Record ID',
  '16': 'Unknown Bank Code',
  '17': 'Invalid Channel',
  '18': 'Wrong Method Call',
  '21': 'No action taken',
  '25': 'Unable to locate record',
  '26': 'Duplicate record',
  '30': 'Format error',
  '34': 'Suspected fraud',
  '35': 'Contact sending bank',
  '51': 'No sufficient funds',
  '57': 'Transaction not permitted to sender',
  '58': 'Transaction not permitted on channel',
  '61': 'Transfer limit Exceeded',
  '63': 'Security violation',
  '65': 'Exceeds withdrawal frequency',
  '68': 'Response received too late',
  '69': 'Unsuccessful Account/Amount block',
  '70': 'Unsuccessful Account/Amount unblock',
  '71': 'Empty Mandate Reference Number',
  '91': 'Beneficiary Bank not available',
  '92': 'Routing error',
  '94': 'Duplicate transaction',
  '96': 'System malfunction',
  '97': 'Timeout waiting for response from destination',
  '31': 'Unable to do TSQ',
  '32': 'Transaction Failed. Resend with new Payment Reference No',
  '19': 'Payment Reference cannot be found',
  '20': 'Transaction in progress. Awaits Confirmation from NIBSS',
  '22': 'Error Occurred Getting Transaction Status',
  '23': 'Payment Reference Exist. Transaction under Investigation',
  '33': 'Exceptions raised during Name Enquiry',
  '36': 'Unable to call main Fund Transfer Service',
  '37': 'Unable to call main Transaction Status Service',
  '38': 'Unable to call main Name Enquiry Service',
  '39': 'Unable to call main Bank List Service',
};
